=== johnylogic/Project-DC/Sample/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Railway">
<xs:complexType>
<xs:sequence>
<xs:element name="Employee" maxOccurs="unbounded">
    <xs:complexType>
    <xs:sequence>
    <xs:element name="Name" type="xs:string"></xs:element>
    <xs:element name="Age" type="xs:integer"></xs:element>
    <xs:element name="Salary" type="MySal"></xs:element>
    <xs:element name="Station" type="xs:string"></xs:element>
    </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="Train" maxOccurs="unbounded">
    <xs:complexType>
    <xs:sequence>
    <xs:element name="Train_no" type="xs:integer"></xs:element>
    <xs:element name="Train_Name" type="xs:string"></xs:element>
    <xs:element name="From" type="xs:string"></xs:element>
    <xs:element name="To" type="xs:string"></xs:element>
    <xs:element name="Arrival" type="xs:time"></xs:element>
    <xs:element name="Departure" type="xs:time"></xs:element>
    <xs:element name="Fare" type="xs:integer"></xs:element>
    </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="Leave" maxOccurs="unbounded">
    <xs:complexType>
    <xs:sequence>
    <xs:element name="Leave_id" type="xs:integer"></xs:element>
    <xs:element name="Name" type="xs:string"></xs:element>
    <xs:element name="Leave_date" type="xs:date"></xs:element>
    <xs:element name="Leave_desc" type="xs:string"></xs:element>\
    </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:sequence>
</xs:complexType>
</xs:element>
<xs:simpleType name="MySal">
<xs:restriction base="xs:integer">
<xs:minInclusive value="10000"></xs:minInclusive>
<xs:maxInclusive value="100000"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>
</xs:schema>

=== johnylogic/Project-DC/Sample/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="test.xsl"?>
<Railway xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="NewXMLSchema.xsd">
  <Employee>
    <Name>ABHIJITH</Name>
    <Age>17</Age>
    <Salary>30000</Salary>
    <Station>Chennai</Station>
  </Employee>
  <Employee>
    <Name>ANUGRAH</Name>
    <Age>33</Age>
    <Salary>45000</Salary>
    <Station>Bengaluru</Station>
  </Employee>
  <Employee>
    <Name>SIDHARTH</Name>
    <Age>32</Age>
    <Salary>36000</Salary>
    <Station>Manglore</Station>
 	</Employee>
 	<Employee>
    <Name>SURAJ</Name>
    <Age>30</Age>
    <Salary>46000</Salary>
    <Station>Mumbai</Station>
 	</Employee>
 
 	<Train>
 	<Train_no>213473</Train_no>
 	<Train_Name>Manglore EXP</Train_Name>
 	<From>Bengaluru</From>
 	<To>Manglore</To>
 	<Arrival>09:00:00</Arrival>
 	<Departure>12:00:00</Departure>
 	<Fare>480</Fare>
 	</Train>
 	<Train>
 	<Train_no>213733</Train_no>
 	<Train_Name>Mumbai EXP</Train_Name>
 	<From>Bengaluru</From>
 	<To>Mumbai</To>
 	<Arrival>12:00:00</Arrival>
 	<Departure>09:00:00</Departure>
 	<Fare>780</Fare>
 	</Train>
 	<Train>
 	<Train_no>103343</Train_no>
 	<Train_Name>Kannur EXP</Train_Name>
 	<From>Manglore</From>
 	<To>Kannur</To>
 	<Arrival>18:00:00</Arrival>
 	<Departure>21:00:00</Departure>
 	<Fare>400</Fare>
 	</Train>
 	<Train>
 	<Train_no>213567</Train_no>
 	<Train_Name>Malabar EXP</Train_Name>
 	<From>Manglore</From>
 	<To>Trivandram</To>
 	<Arrival>06:00:00</Arrival>
 	<Departure>24:00:00</Departure>
 	<Fare>1050</Fare>
 	</Train>
 	
 	<Leave>
 	<Leave_id>1</Leave_id>
	<Name>ABHIJITH</Name>
 	<Leave_date>2021-10-24</Leave_date>
 	<Leave_desc>Pending</Leave_desc>
 	</Leave>
 	<Leave>
 	<Leave_id>2</Leave_id>
	<Name>SIDHARTH</Name>
 	<Leave_date>2021-09-14</Leave_date>
 	<Leave_desc>Approved</Leave_desc>
 	</Leave>
 	<Leave>
 	<Leave_id>1</Leave_id>
	<Name>SURAJ</Name>
 	<Leave_date>2021-07-09</Leave_date>
 	<Leave_desc>Pending</Leave_desc>
 	</Leave>
 	
</Railway>
